-- ============================================================
-- Sellence Revenue Tracker — Supabase Schema + Seed
-- Run this entire file in the Supabase SQL Editor
-- ============================================================

-- Tables
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD',
  model TEXT NOT NULL DEFAULT 'FIXED',
  status TEXT NOT NULL DEFAULT 'Active',
  start_date TEXT,
  fixed_fee REAL NOT NULL DEFAULT 0,
  per_unit_rate REAL NOT NULL DEFAULT 0,
  min_fee REAL NOT NULL DEFAULT 0,
  max_fee REAL NOT NULL DEFAULT 0,
  tiers JSONB NOT NULL DEFAULT '[]',
  addon1 REAL NOT NULL DEFAULT 0,
  addon2 REAL NOT NULL DEFAULT 0,
  twilio_sid TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS usage_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  month TEXT NOT NULL,
  metric TEXT NOT NULL,
  value REAL NOT NULL DEFAULT 0,
  notes TEXT,
  UNIQUE(client_id, month, metric)
);

CREATE TABLE IF NOT EXISTS monthly_revenue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  month TEXT NOT NULL,
  calculated_usd REAL NOT NULL DEFAULT 0,
  manual_usd REAL,
  revenue_status TEXT NOT NULL DEFAULT 'committed',
  invoice_ref TEXT,
  notes TEXT,
  UNIQUE(client_id, month)
);

CREATE TABLE IF NOT EXISTS sms_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  month TEXT NOT NULL,
  sms_count REAL NOT NULL DEFAULT 0,
  twilio_cost REAL,
  UNIQUE(client_id, month)
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Disable RLS (no auth yet)
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE usage_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_revenue DISABLE ROW LEVEL SECURITY;
ALTER TABLE sms_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;

-- Settings defaults
INSERT INTO settings (key, value) VALUES
  ('exchange_rate', '3.6'),
  ('twilio_cost_per_sms', '0.007'),
  ('sms_bill_rate', '0.008')
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- Clients seed
-- ============================================================
INSERT INTO clients (id, name, currency, model, status, fixed_fee, per_unit_rate, min_fee, max_fee, tiers, addon1, addon2, twilio_sid, notes) OVERRIDING SYSTEM VALUE VALUES
(1,  'Panda',              'NIS','TIERED_SALES','Active',  2000, 0,    0,    0,    '[{"limit":100,"price":25},{"limit":200,"price":35},{"limit":300,"price":45}]', 0,    0,    null, 'Base + tiered per sale'),
(2,  'Libra',              'NIS','FIXED_ADDON', 'Active',  13000,0,    0,    0,    '[]', 4000, 4000, null, '₪13K car base + ₪4K apartment + ₪4K new clients'),
(3,  'Calltact',           'NIS','FIXED',       'Paused',  500,  0,    0,    0,    '[]', 0,    0,    null, 'Paused'),
(4,  'Allstars',           'USD','PLAN_PLUS',   'Active',  1000, 0,    0,    0,    '[]', 15,   150,  null, '$500/mo + $15/meeting + $150/sale'),
(5,  'Voom',               'USD','PER_UNIT',    'Active',  0,    2,    0,    1000, '[]', 0,    0,    null, '$2/policy max $1K'),
(6,  'Palais des Thes',    'USD','TIERED_REL',  'Active',  0,    0,    0,    0,    '[{"limit":500,"price":1000},{"limit":1000,"price":1800},{"limit":2000,"price":3200},{"limit":3000,"price":4200},{"limit":4000,"price":4800}]', 0, 0, null, 'Rel tiers — sits at floor'),
(7,  'BPM',                'NIS','FIXED',       'Active',  1800, 0,    0,    0,    '[]', 0,    0,    null, '1800 NIS/mo'),
(8,  'Heavys',             'USD','PER_CONV',    'Active',  0,    1.2,  200,  0,    '[]', 0,    0,    null, '$1.20/conv min $200'),
(9,  'Miamily',            'USD','TIERED_CONV', 'Active',  0,    0,    0,    0,    '[{"limit":250,"price":500},{"limit":500,"price":1000},{"limit":750,"price":1350},{"limit":1000,"price":1600},{"limit":1500,"price":2100},{"limit":2000,"price":2800}]', 0, 0, null, 'Standard conv tiers'),
(10, 'Shade It',           'USD','TIERED_CONV', 'Active',  0,    0,    0,    0,    '[{"limit":250,"price":500},{"limit":500,"price":1000},{"limit":750,"price":1350},{"limit":1000,"price":1600},{"limit":1500,"price":2100},{"limit":2000,"price":2800}]', 0, 0, null, 'Standard conv tiers'),
(11, 'Evinature',          'USD','TIERED_CONV', 'Active',  0,    0,    0,    0,    '[{"limit":250,"price":500},{"limit":500,"price":1000},{"limit":750,"price":1350},{"limit":1000,"price":1600},{"limit":1500,"price":2100},{"limit":2000,"price":2800}]', 0, 0, null, 'Standard conv tiers'),
(12, 'Askrx / Beluga',     'USD','FIXED',       'Reduced', 150,  0,    0,    0,    '[]', 0,    0,    null, '$150 reduced'),
(13, 'Leveraged',          'USD','TIERED_CONV', 'Active',  0,    0,    0,    0,    '[{"limit":250,"price":500},{"limit":500,"price":1000},{"limit":750,"price":1350},{"limit":1000,"price":1600},{"limit":1500,"price":2100},{"limit":2000,"price":2800}]', 0, 0, null, 'Standard conv tiers'),
(14, 'Israel Canada',      'USD','PLAN_PLUS',   'Active',  1000, 0,    0,    0,    '[]', 15,   150,  null, '$1K base + $15/meeting + $150/sale'),
(15, 'United Support',     'USD','TIERED_CONV', 'Churned', 0,    0,    0,    0,    '[{"limit":250,"price":500},{"limit":500,"price":1000},{"limit":750,"price":1350},{"limit":1000,"price":1600},{"limit":1500,"price":2100},{"limit":2000,"price":2800}]', 0, 0, null, 'Standard conv tiers'),
(16, 'Honeybook',          'USD','TIERED_REL',  'Active',  3000, 0,    0,    0,    '[{"limit":500,"price":1000},{"limit":1000,"price":1800},{"limit":2000,"price":3200},{"limit":3000,"price":4200},{"limit":4000,"price":4800}]', 0, 0, null, 'Rel tiers + $3K SDR'),
(17, 'Best Brilliance',    'USD','TIERED_REL',  'Active',  0,    0,    0,    0,    '[{"limit":500,"price":1000},{"limit":1000,"price":1800},{"limit":2000,"price":3200},{"limit":3000,"price":4200},{"limit":4000,"price":4800}]', 0, 0, null, 'Rel tiers'),
(18, 'Headphones',         'USD','TIERED_CONV', 'Active',  0,    0,    0,    0,    '[{"limit":250,"price":500},{"limit":500,"price":1000},{"limit":750,"price":1350},{"limit":1000,"price":1600},{"limit":1500,"price":2100},{"limit":2000,"price":2800}]', 0, 0, null, 'Standard conv tiers'),
(19, 'Sela',               'NIS','FIXED',       'Pilot',   5000, 0,    0,    0,    '[]', 0,    0,    null, '5000 NIS pilot'),
(20, 'Cleandot',           'USD','TIERED_CONV', 'Active',  0,    0,    0,    0,    '[{"limit":250,"price":500},{"limit":500,"price":1000},{"limit":750,"price":1350},{"limit":1000,"price":1600},{"limit":1500,"price":2100},{"limit":2000,"price":2800}]', 0, 0, null, 'Standard conv tiers'),
(21, 'Roxy-Moxy',          'USD','FIXED',       'Pilot',   1500, 0,    0,    0,    '[]', 0,    0,    null, '$1500/mo pilot'),
(22, 'eTeacher',           'USD','HYBRID',      'Active',  0,    0.15, 1500, 0,    '[]', 15,   0,    null, '$0.15/rel + $15/sale, min $1500'),
(23, 'Particle',           'USD','TIERED_REL',  'Active',  0,    0,    0,    0,    '[{"limit":500,"price":1000},{"limit":1000,"price":1800},{"limit":2000,"price":3200},{"limit":3000,"price":4200},{"limit":4000,"price":4800}]', 0, 0, null, 'Rel tiers'),
(24, 'Sweetch',            'USD','FIXED',       'Active',  500,  0,    0,    0,    '[]', 0,    0,    null, '$500/mo fixed'),
(25, 'Hulken',             'USD','TIERED_CONV', 'Active',  0,    0,    0,    0,    '[{"limit":250,"price":500},{"limit":500,"price":1000},{"limit":750,"price":1350},{"limit":1000,"price":1600},{"limit":1500,"price":2100},{"limit":2000,"price":2800}]', 0, 0, null, 'Custom conv tiers'),
(26, 'Opt Health',         'USD','FIXED',       'Pilot',   1000, 0,    0,    0,    '[]', 0,    0,    null, 'Signed pilot'),
(27, 'Bina',               'USD','FIXED',       'Pipeline',500,  0,    0,    0,    '[]', 0,    0,    null, null),
(28, 'Targeta',            'USD','FIXED',       'Pipeline',1000, 0,    0,    0,    '[]', 0,    0,    null, null),
(29, 'Generali Insurance', 'USD','FIXED',       'Pipeline',5000, 0,    0,    0,    '[]', 0,    0,    null, null),
(30, 'Tailor Brands',      'USD','FIXED',       'Pipeline',1000, 0,    0,    0,    '[]', 0,    0,    null, 'Wix affiliate')
ON CONFLICT (id) DO NOTHING;

-- Reset sequence so new inserts get id > 30
SELECT setval(pg_get_serial_sequence('clients', 'id'), 30);

-- ============================================================
-- Historical revenue seed (from Excel, NIS converted at 3.0)
-- ============================================================
INSERT INTO monthly_revenue (client_id, month, calculated_usd, revenue_status) VALUES
-- Panda (NIS/3)
(1,'2025-05',4451.67,'invoiced'),(1,'2025-06',7166.67,'invoiced'),(1,'2025-07',8261.67,'invoiced'),
(1,'2025-08',5126.67,'invoiced'),(1,'2025-09',5531.67,'invoiced'),(1,'2025-10',8081.67,'invoiced'),
(1,'2025-11',13661.67,'invoiced'),(1,'2025-12',6056.67,'invoiced'),(1,'2026-01',3416.67,'invoiced'),
(1,'2026-02',8606.67,'invoiced'),(1,'2026-03',8846.67,'committed'),(1,'2026-04',6341.67,'committed'),
-- Libra (NIS/3)
(2,'2025-05',4333.33,'invoiced'),(2,'2025-06',4333.33,'invoiced'),(2,'2025-07',4333.33,'invoiced'),
(2,'2025-08',4333.33,'invoiced'),(2,'2025-09',5666.67,'invoiced'),(2,'2025-10',5666.67,'invoiced'),
(2,'2025-11',5666.67,'invoiced'),(2,'2025-12',5666.67,'invoiced'),(2,'2026-01',5666.67,'invoiced'),
(2,'2026-02',5333.33,'invoiced'),(2,'2026-03',5333.33,'committed'),(2,'2026-04',5333.33,'committed'),
-- Calltact (NIS/3)
(3,'2025-05',166.67,'invoiced'),(3,'2025-06',166.67,'invoiced'),(3,'2025-07',166.67,'invoiced'),
(3,'2025-08',166.67,'invoiced'),(3,'2025-09',166.67,'invoiced'),(3,'2025-10',166.67,'invoiced'),
(3,'2025-11',166.67,'invoiced'),(3,'2025-12',166.67,'invoiced'),
-- Allstars (USD)
(4,'2025-05',500,'invoiced'),(4,'2025-06',500,'invoiced'),(4,'2025-07',500,'invoiced'),
(4,'2025-08',500,'invoiced'),(4,'2025-09',500,'invoiced'),(4,'2025-10',500,'invoiced'),
(4,'2025-11',500,'invoiced'),(4,'2025-12',500,'invoiced'),(4,'2026-01',630,'invoiced'),
(4,'2026-02',560,'invoiced'),(4,'2026-03',585,'committed'),
-- Voom (USD)
(5,'2025-05',48,'invoiced'),(5,'2025-06',44,'invoiced'),(5,'2025-07',30,'invoiced'),
(5,'2025-08',36,'invoiced'),(5,'2025-09',34,'invoiced'),(5,'2025-10',28,'invoiced'),
(5,'2025-11',16,'invoiced'),(5,'2025-12',14,'invoiced'),(5,'2026-01',94,'invoiced'),
(5,'2026-02',24,'invoiced'),(5,'2026-03',40,'committed'),(5,'2026-04',26,'committed'),
-- Palais des Thes (USD)
(6,'2025-05',500,'invoiced'),(6,'2025-06',500,'invoiced'),(6,'2025-07',500,'invoiced'),
(6,'2025-08',500,'invoiced'),(6,'2025-09',500,'invoiced'),(6,'2025-10',500,'invoiced'),
(6,'2025-11',500,'invoiced'),(6,'2025-12',500,'invoiced'),(6,'2026-01',500,'invoiced'),
(6,'2026-02',500,'invoiced'),(6,'2026-03',500,'committed'),(6,'2026-04',500,'committed'),
-- BPM (NIS/3)
(7,'2025-05',1376.67,'invoiced'),(7,'2025-06',900,'invoiced'),(7,'2025-07',1790,'invoiced'),
(7,'2025-08',2266.67,'invoiced'),(7,'2025-09',1600,'invoiced'),(7,'2025-10',600,'invoiced'),
(7,'2025-11',600,'invoiced'),(7,'2025-12',600,'invoiced'),(7,'2026-01',600,'invoiced'),(7,'2026-02',600,'invoiced'),
-- Heavys (USD)
(8,'2025-05',559.2,'invoiced'),(8,'2025-06',906,'invoiced'),(8,'2025-07',908.4,'invoiced'),
(8,'2025-08',586.8,'invoiced'),(8,'2025-09',630,'invoiced'),(8,'2025-10',1039.2,'invoiced'),
(8,'2025-11',1768.8,'invoiced'),(8,'2025-12',1680,'invoiced'),(8,'2026-01',916.8,'invoiced'),
(8,'2026-02',668.4,'invoiced'),(8,'2026-03',756,'committed'),(8,'2026-04',500,'committed'),
-- Miamily (USD)
(9,'2025-08',500,'invoiced'),(9,'2025-09',500,'invoiced'),(9,'2025-10',500,'invoiced'),
(9,'2025-11',500,'invoiced'),(9,'2025-12',500,'invoiced'),(9,'2026-01',500,'invoiced'),
(9,'2026-02',500,'invoiced'),(9,'2026-03',500,'committed'),(9,'2026-04',500,'committed'),
-- Shade It (USD)
(10,'2025-09',500,'invoiced'),(10,'2025-10',500,'invoiced'),(10,'2025-11',500,'invoiced'),
(10,'2025-12',500,'invoiced'),(10,'2026-01',500,'invoiced'),(10,'2026-02',500,'invoiced'),
(10,'2026-03',500,'committed'),(10,'2026-04',500,'committed'),
-- Evinature (USD)
(11,'2025-09',500,'invoiced'),(11,'2025-10',500,'invoiced'),(11,'2025-11',500,'invoiced'),
(11,'2025-12',500,'invoiced'),(11,'2026-01',500,'invoiced'),(11,'2026-02',500,'invoiced'),(11,'2026-03',500,'committed'),
-- Askrx (USD)
(12,'2025-09',150,'invoiced'),(12,'2025-10',150,'invoiced'),(12,'2025-11',150,'invoiced'),
(12,'2025-12',150,'invoiced'),(12,'2026-01',150,'invoiced'),(12,'2026-02',150,'invoiced'),
(12,'2026-03',150,'committed'),(12,'2026-04',150,'committed'),
-- Leveraged (USD)
(13,'2025-09',1000,'invoiced'),(13,'2025-10',500,'invoiced'),(13,'2025-11',500,'invoiced'),
(13,'2025-12',500,'invoiced'),(13,'2026-01',1600,'invoiced'),(13,'2026-02',1600,'invoiced'),
(13,'2026-03',1350,'committed'),(13,'2026-04',500,'committed'),
-- Israel Canada (USD)
(14,'2025-09',1000,'invoiced'),(14,'2025-10',1000,'invoiced'),(14,'2025-11',1000,'invoiced'),
(14,'2025-12',1345,'invoiced'),(14,'2026-01',1780,'invoiced'),(14,'2026-02',1240,'invoiced'),
(14,'2026-03',1450,'committed'),(14,'2026-04',1450,'committed'),
-- United Support (USD)
(15,'2025-10',500,'invoiced'),(15,'2025-11',500,'invoiced'),(15,'2025-12',500,'invoiced'),(15,'2026-01',500,'invoiced'),
-- Honeybook (USD)
(16,'2025-11',1000,'invoiced'),(16,'2025-12',1000,'invoiced'),(16,'2026-01',4000,'invoiced'),
(16,'2026-02',4000,'invoiced'),(16,'2026-03',4000,'committed'),(16,'2026-04',4000,'committed'),
-- Best Brilliance (USD)
(17,'2025-11',1000,'invoiced'),(17,'2025-12',1000,'invoiced'),(17,'2026-01',1000,'invoiced'),
(17,'2026-02',1000,'invoiced'),(17,'2026-03',1000,'committed'),(17,'2026-04',1000,'committed'),
-- Headphones (USD)
(18,'2025-11',500,'invoiced'),(18,'2025-12',500,'invoiced'),(18,'2026-01',500,'invoiced'),
(18,'2026-02',500,'invoiced'),(18,'2026-03',500,'committed'),(18,'2026-04',500,'committed'),
-- Sela (NIS/3)
(19,'2025-12',1666.67,'invoiced'),(19,'2026-01',1666.67,'invoiced'),(19,'2026-02',1666.67,'invoiced'),
(19,'2026-03',1666.67,'committed'),(19,'2026-04',1666.67,'committed'),
-- Cleandot (USD)
(20,'2026-01',500,'invoiced'),(20,'2026-02',500,'invoiced'),(20,'2026-03',500,'committed'),(20,'2026-04',500,'committed'),
-- Roxy-Moxy (USD)
(21,'2026-03',1500,'committed'),(21,'2026-04',1500,'committed'),
-- eTeacher (USD)
(22,'2026-02',1500,'invoiced'),(22,'2026-03',1500,'committed'),(22,'2026-04',1500,'committed'),
-- Particle (USD)
(23,'2026-02',1000,'invoiced'),(23,'2026-03',1800,'committed'),(23,'2026-04',1000,'committed'),
-- Sweetch (USD)
(24,'2026-01',500,'invoiced'),(24,'2026-02',500,'invoiced'),(24,'2026-03',500,'committed'),
-- Hulken (USD)
(25,'2026-03',500,'committed'),(25,'2026-04',500,'committed')
ON CONFLICT (client_id, month) DO NOTHING;
